version: '3'
services:
  app:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-server:1.1.9-local-ui-graph-dev
    env_file:
     - .env
    environment:
     - SERVICE_PORT=5001
     - GRAPHQL_URL=http://local-ui-graph.repoflow-container-graph.com:4001/graphql
     - EVENTS_URL=http://local-ui-graph.repoflow-container-graph.com:4001/events
    ports:
     - "5001:5001"
